[package]
name = "senobi-library"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield-struct = "0.11.0"
either = "1.15.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
ordered-float = "5.1.0"
snafu = "0.8.9"
szs = "0.3.7"
zerocopy = { version = "0.8.27", features = ["derive"] }
